### PR TITLE
Bugfix: Hanging of websocket task on HTTPStatus error exception

### PR DESCRIPTION
**Pull request by nanosonde**
Hopefully fixes https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/121

### CODE REVIEW

**Comment by nanosonde** [comment]
Concerning the exceptions:
I think it would be best if the Gardena integration removes any dependencies to the OAUTH2 things like here: https://github.com/py-smart-gardena/hass-gardena-smart-system/blob/6d76239c81ed622fb027f1711173d747f85b30d2/custom_components/gardena_smart_system/__init__.py#L14
And instead defines its own exceptions.

Furthermore, in the integration there is no try/catch block surrounding this: https://github.com/py-smart-gardena/hass-gardena-smart-system/blob/6d76239c81ed622fb027f1711173d747f85b30d2/custom_components/gardena_smart_system/__init__.py#L62

With this PR it is not really necessary as the websaocket task handles them and automatically restarts things. But maybe we want to define again our exception that we could raise after having retried for some timeout without success.

**Comment by grm** [comment]
Thx for the PR ! By reading it it should solve one edge case (but not solve the root of the 429 issues i guess .. )

I will try it tonight and I also have an idea for the source of these 429. I ll try it tonight also !
Thx again ! 

I may have

**Comment by nanosonde** [comment]
My guess is that you cannot really influence the 429 issue.
It just happens from time to time. Maybe the Gardena people have just a limited number of resources available.

The only thing I could think would be that we would have to reuse the websocket connection URL again after it is being closed.
But then again, I read that the URL is only valid for a few seconds. So when the connection was established for 2h I think it wonÄt be valid anymore. As a result we would have to contact their Gardena at least every two hours.
I only get the 429 from the Gardena API. So far I never got it from the authentciation API.

**Comment by nanosonde** [comment]
Just happened again:
```
device update: <gardena.devices.sensor.Sensor object at 0x7ff2480fa910>
2022-07-21 19:18:27 DEBUG    Closing websocket ..
2022-07-21 19:18:27 DEBUG    Sleeping 10 seconds ..
2022-07-21 19:18:37 DEBUG    Trying to connect to gardena API....
2022-07-21 19:18:37 DEBUG    Trying to get Websocket url
oauth_client.py: ensure_active_token()
2022-07-21 19:18:37 DEBUG    HTTP Request: POST https://api.smart.gardena.dev/v1/websocket "HTTP/1.1 429 "
2022-07-21 19:18:37 DEBUG    Websocket url: got response
2022-07-21 19:18:37 DEBUG    HTTPStatusError ..
2022-07-21 19:18:37 DEBUG    Closing websocket ..
2022-07-21 19:18:37 DEBUG    Sleeping 10 seconds ..
2022-07-21 19:18:47 DEBUG    Trying to connect to gardena API....
2022-07-21 19:18:47 DEBUG    Trying to get Websocket url
oauth_client.py: ensure_active_token()
2022-07-21 19:18:47 DEBUG    HTTP Request: POST https://api.smart.gardena.dev/v1/websocket "HTTP/1.1 201 Created"
2022-07-21 19:18:47 DEBUG    Websocket url: got response
2022-07-21 19:18:47 DEBUG    Websocket url retrieved successfully
2022-07-21 19:18:47 DEBUG    Connecting to websocket ..
2022-07-21 19:18:48 DEBUG    Connected !
device update: <gardena.devices.sensor.Sensor object at 0x7ff24896cfa0>
```

**Comment by nanosonde** [comment]
Maybe another thing: what about the websocket ping interval?
> we recommend sending ping messages every 150 seconds to keep the connection open

**Comment by grm** [comment]
Yes, that was my guess.

I think this is the sole request we are doing and doign it every 10 seconds.
I was planning to change that tonight ;)

**Comment by grm** [comment]
429 codes means client errors, the api is not responding.
I think we have a behaviour wich request the API too often, and i only see the ping ..

**Comment by nanosonde** [comment]
Please also read this interesting page:
https://www.useanvil.com/blog/engineering/throttling-and-consuming-apis-with-429-rate-limits/

Do we also receive a „retry-after“ http header field?
This eould easily solve it.

**Comment by stromnet** [comment]
The approach merged here will, instead of backing of in case of a 429 Limit Exceeded error, hammer the server forever. Which will most likely make it block forever. So now the application will be broken more or less totally, until killed and left idle for some time (assuming the APIs rate limits works as expected) :) 

See this section:
https://developer.husqvarnagroup.cloud/apis/gardena-smart-system-api#rate-limits

> An application that behaves as a good citizen of the Gardena eco system should not exceed the following limits:
>    * On average one call every fifteen minutes.
>    * 3'000 requests per month.

**Comment by stromnet** [comment]
If there is no Retry-After header in case of 429, I would sleep N=2 seconds or so, then retry. Then if it fails with 429 again, incresae the wait time a bit for each failure, until successful call (in which case back-off value is reset, until we get 429 in future).

**Comment by stromnet** [comment]
Also, perhaps build it into lower-level functions such as `__call_smart_system_get` and `call_smart_system_service`.

**Comment by grm** [comment]
I agree, we should have a backoff timeout in case of 429 !

I am looking at the possibility to implement suche a feature.

**Comment by stromnet** [comment]
Worth mentioning, the recommendations specified by Gardena does not reflect the way it's actually working.
Today I got a 429 on the websocket call, at 22:32:57... The only previous call was another websocket call at 20:32:46 (and before that 18:32, 16:32,14:32, all which gave 201 Created).. A lot fewer than "one call per every 15 minutes", and since the subsequent call 15 seconds later (my backoff logic) passed fine, probably not near the 3k/req month either.

**Comment by nanosonde** [comment]
> (my backoff logic) passed fine

Could you open another PR which adds the backoff logic for all?

**Comment by stromnet** [comment]
> > (my backoff logic) passed fine
> 
> Could you open another PR which adds the backoff logic for all?

My "backoff logic" is more of a hack: catch those exceptions outside of my (small) program's main loop and just restart the whole thing. So not really something that can be PR'd.
For the record, it looks like this (quick evening hack just to get things recovering automatically):

```
backoff = 10
while True:
    try:
        asyncio.run(main())
        break
    except httpx.HTTPStatusError as e:
        if e.response.status_code != 429:
            raise
        logging.exception('HTTPStatusError')
    except Exception as e:
        if e.args[0] != "Limit Exceeded":
            raise
        logging.exception('anon exec')

    logging.warning("Gardena API limit exceeded.. global retrying in %d...", backoff)
    time.sleep(backoff)
    backoff = min(backoff * 1.5, 3600)
```

oh and then inside main(), after first successful call I set `backoff = 10`.
Did I say hacky? :see_no_evil:

**Comment by grm** [comment]
Hello, 


I just implement a backoff mechanism in the library yesterday in the beta channel (b906). It may be a little aggressive for now but it is less that it is now ;)

**Comment by grm** [comment]
It is implmeented only on get for data, on uthentication and on websocket url retrieval.

I am not sure I want to have this mechanisme for service calls (e.g. start mower, watering ...)

**Comment by stromnet** [comment]
If the on_exception decorator can be made to filter on only 429's (as in their `giveup=fatal_code` [example](https://github.com/litl/backoff#examples) perhaps) , I'd say that looks like a good solution. *perhaps* also for 503?
Unsure about PUTs..
For a  404 or 400 or something else, I don't think it should retry for any kind of calls.

**Comment by nanosonde** [comment]
> I am not sure I want to have this mechanism for service calls (e.g. start mower, watering ...)

I would not want to have this as it seems dangerous to me. I do not want to start the mower at an unknown time in the future when the conditions to start it are not known anymore. For example.

Instead I would do like this dev here: https://github.com/ekutner/home-connect-hass
He connect to the Bosch/Siemens REST API for Home Connect devices. They also have rate limits.

He added a dedicated device for the REST API which gives a status: 
* INIT - The integration is initializing
* RUNNING - The integration has started running
* LOADED - The integration finished loading the initial data from the Home Connect service
* READY - The integration has successfully subscribed to real time updates from the cloud service and is now fully functional.
* BLOCKED - The Home Connect service has blockde additional API calls for a period of time due to exceeding the service rate limits It may take up to one minute to go from LOADED to READY

This would be perfectly well here as well.

If blocked the user has to decided in his/her automation what to do.

**Comment by nanosonde** [comment]
BTW: He is lucky as he gets a "retry-after" header: https://github.com/ekutner/home-connect-async/blob/a907d3c2ca39e96610f66cfabada9b868663567a/home_connect_async/api.py#L85

**Comment by stromnet** [comment]
Would it make sense to add retry for other errors too?

My python code had crashed:
```
Traceback (most recent call last):
  File "test.py", line 303, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 253, in main
    await smart_system.start_ws(location)
  File "/usr/home/johan/dev/gardena-async/py-smart-gardena/src/gardena/smart_system.py", line 189, in start_ws
    ws_url = await self.__get_ws_url(location)
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/home/johan/dev/gardena-async/py-smart-gardena/src/gardena/smart_system.py", line 216, in __get_ws_url
    data=json.dumps(args, ensure_ascii=False),
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_client.py", line 1855, in post
    extensions=extensions,
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 92, in request
    method, url, auth=auth, **kwargs)
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_client.py", line 1618, in send
    history=[],
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    history=history,
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/home/johan/dev/gardena-async/venv/lib/python3.7/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
```

**Pull request merged**
